
   
blank_issues_enabled: true
contact_links:
  - name: Add new ToDo
    about: made by config.yml
    # edit {username} and {repo} for your environment
    url: https://github.com/enomotoryota/MyDream50/issues/new?template=custom.md&projects=enomotoryota%2FToDo%2F1&labels=MyDream50
